In [1]:
import numpy as np 

In [2]:
weights=np.array([58,59,84,61])
heights=np.array([1,1.2,1.5,0.9])

In [6]:
%%time
np.dot(weights,heights)

CPU times: total: 0 ns
Wall time: 88.2 μs


np.float64(309.7)

In [4]:
(weights*heights).sum()

np.float64(309.7)

In [5]:
weights*heights

array([ 58. ,  70.8, 126. ,  54.9])

matrix multiplication

In [7]:
climate=np.array([[1,2,3],[2,3,4],[3,4,5]])

In [8]:
weight=np.array([1,2,3])

In [9]:
np.matmul(climate,weight)

array([14, 20, 26])

In [10]:
climate @ weight

array([14, 20, 26])