In [2]:
import numpy as np

In [3]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3]])

In [4]:
arr3=np.array([[11,12,13,14],[15,16,17,18],[19,11,12,13]])

In [5]:
arr2+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [6]:
arr3-arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [7]:
arr2%4

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]])

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [9]:
arr2.shape

(3, 4)

In [10]:
arr4=np.array([4,5,6,7])

In [11]:
arr4.shape

(4,)

In [12]:
arr2+arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [13]:
arr5=np.array([7,8])

In [14]:
arr2 +arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [15]:
arr2!=arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [18]:
arr6=np.array([1,2,3,4])

In [19]:
arr2==arr6

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [23]:
(arr2==arr6).sum()

np.int64(4)

In [20]:
arr2<arr6

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [21]:
arr2>=arr6

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False, False]])