In [2]:
import numpy as np

In [5]:
# create a 3x2x4 3D array with sequential values
arr_3d = np.arange(1,3 * 2 * 4*2,2).reshape(3, 2, 4)
arr_3d

array([[[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]],

       [[17, 19, 21, 23],
        [25, 27, 29, 31]],

       [[33, 35, 37, 39],
        [41, 43, 45, 47]]])

In [6]:
arr_3d.shape

(3, 2, 4)

In [8]:
# single ele
arr_3d[2,1,3]

np.int64(47)

In [9]:
# subarray using ranges
arr_3d[1:, 0:1, :2]

array([[[17, 19]],

       [[33, 35]]])

In [10]:
arr_3d[1:, 0:1, 2]

array([[21],
       [37]])

In [11]:
arr_3d[:2,1]

array([[ 9, 11, 13, 15],
       [25, 27, 29, 31]])

creating numpy arrays

In [13]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# random vector
np.random.rand(5)

array([0.78362795, 0.89008659, 0.70280893, 0.81248238, 0.75333518])

In [17]:
# random matrix
np.random.rand(2,3)

array([[0.73957535, 0.62114929, 0.97073158],
       [0.80869501, 0.38964991, 0.31705702]])

In [23]:
# random matrix
np.random.randn(2,3)

array([[ 0.01351718, -0.52398766, -1.29293651],
       [-1.15683617, -0.12091316,  0.49029384]])

In [24]:
np.full([2,3],42)

array([[42, 42, 42],
       [42, 42, 42]])

In [34]:
np.arange(10,90,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [35]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [32]:
np.linspace(0,40,11)

array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40.])