In [1]:
w1,w2,w3= 0.3,0.2,0.5

In [2]:
kanto=[73,67,38]
johto=[85,78,50]
hoenn=[70,64,45]
sinnoh=[90,88,60]
unova=[95,80,55]

In [3]:
weights=[w1,w2,w3]

In [4]:
def crop_yield(region, weights):
    result=0
    for x,w in zip(region , weights):
        result+= x*w
    return result

In [5]:
crop_yield(johto , weights)

66.1

In [6]:
import numpy as np

In [7]:
kanto=np.array([73,67,38])
johto=np.array([85,78,50])
hoenn=np.array([70,64,45])
sinnoh=np.array([90,88,60])
unova=np.array([95,80,55])

In [10]:
type(kanto)

numpy.ndarray

In [11]:
np.dot(kanto, weights)

np.float64(54.3)

In [8]:
kanto*weights

array([21.9, 13.4, 19. ])

In [9]:
(kanto*weights).sum()

np.float64(54.3)

In [12]:
arr1= list(range(1000000))
arr2=list(range(1000000,2000000))

# numpy array
arr1_np=np.array(arr1)
arr2_np=np.array(arr2)

In [13]:
%%time
result=0
for x,y in zip(arr1,arr2):
    result+=x*y
result

CPU times: total: 156 ms
Wall time: 166 ms


833332333333500000

In [14]:
%%time
np.dot(arr1_np,arr2_np)

CPU times: total: 0 ns
Wall time: 3.19 ms


np.int64(833332333333500000)

Multi dimensional array

In [15]:
climate_data=np.array([[73,67,43],
                       [91,88,64],
                       [87,134,58]])

In [16]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58]])

In [17]:
climate_data.shape

(3, 3)

In [20]:
weight=np.array(weights)

In [21]:
weight.shape

(3,)

In [22]:
arr3=np.array([[[73,67,43],
                [91,88,64]],
                [[73,67,43],
                [91,88,64]]])

In [23]:
arr3.shape

(2, 2, 3)

In [24]:
weight.dtype

dtype('float64')

In [26]:
arr4=np.array([[[73,67,43],
                [91,88,64]],
                [[73,67,43],
                [91,88,64.2]]])

In [29]:
arr3.dtype

dtype('int64')

In [30]:
arr4.dtype

dtype('float64')

In [31]:
arr4

array([[[73. , 67. , 43. ],
        [91. , 88. , 64. ]],

       [[73. , 67. , 43. ],
        [91. , 88. , 64.2]]])

In [32]:
np.matmul(climate_data,weight)

array([56.8, 76.9, 81.9])

In [33]:
climate_data @ weight

array([56.8, 76.9, 81.9])