Working with csv file

In [14]:
import numpy as np

In [15]:
climate_data= np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [16]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       [84., 63., 38.],
       [66., 50., 52.],
       [41., 94., 77.],
       [91., 57., 96.],
       [49., 96., 99.],
       [67., 20., 28.]])

In [17]:
climate_data.shape

(9, 3)

In [18]:
weights=np.array([0.3,0.2,0.5])

In [19]:
yields=climate_data @ weights

In [20]:
yields

array([72.2, 59.7, 65.2, 56.8, 55.8, 69.6, 86.7, 83.4, 38.1])

In [21]:
yields.shape

(9,)

We can now add the yields back to climate_data as a fourth column using the
function. np.concatenate *****


np.reshape ***** used to change the shape like (9,) to (9,1) 


In [22]:
climate_results=np.concatenate((climate_data,yields.reshape(9,1)),axis=1)

In [23]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       [84. , 63. , 38. , 56.8],
       [66. , 50. , 52. , 55.8],
       [41. , 94. , 77. , 69.6],
       [91. , 57. , 96. , 86.7],
       [49. , 96. , 99. , 83.4],
       [67. , 20. , 28. , 38.1]])

practice on concatenation

In [24]:
# Create two 2x2 arrays
arr1 = np.array([[1, 2],
                [3, 4]])

arr2 = np.array([[5, 6],
                [7, 8]])

# Concatenate along axis=0 (vertically)
concat_axis_0 = np.concatenate((arr1, arr2), axis=0)
print("Concatenated along axis 0:\n", concat_axis_0)

# Concatenate along axis=1 (horizontally)
concat_axis_1 = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenated along axis 1:\n", concat_axis_1)

Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


practice on reshape

In [25]:
# Create a 1D array with 12 elements
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

print(arr)
# Reshape to a 3x4 2D array
reshaped_2d = np.reshape(arr, (3, 4))
print("Reshaped to 3x4:\n", reshaped_2d)

# Reshape using -1 for an inferred dimension
reshaped_inferred = np.reshape(arr, (2, -1))
print("\nReshaped with inferred dimension:\n", reshaped_inferred)

# Flatten an array using -1
flattened_arr = np.reshape(reshaped_2d, -1)
print("\nFlattened array:\n", flattened_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped with inferred dimension:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


to save back csv in file

In [26]:
np.savetxt('climate.txt',climate_results,fmt='%.2f',
           header='temprature,rainfall,humidity,yield_apples',comments='')

. Mathematics: np.sum, np.exp , np. round , arithemtic operators
· Array manipulation: np.reshape, np.stack, np.concatenate, np.split
. Linear Algebra: np.matmul , np.dot , np.transpose, np.eigvals
. Statistics: np.mean , np.median, np.std, np.max
